# Generated by Django 5.0.3 on 2024-05-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_query', models.CharField(max_length=255)),
                ('question_id', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
            ],
        ),
    ]
