# Generated by Django 5.0.3 on 2024-05-13 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_search_question_text_alter_search_search_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публикации'),
        ),
    ]
